name             'clamav-cookbook'
maintainer       'greg palmier'
maintainer_email 'gregpalmier@gmail.com'
license          'All rights reserved'
description      'Installs/Configures clamav-cookbook'
long_description 'Installs/Configures clamav-cookbook'
version          '0.1.0'
depends		 'apt'
depends		 'cron'
